//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Animals
    {
        public int ID { get; set; }
        public string Title { get; set; }
        public string Kingdom { get; set; }
        public string Type { get; set; }
        public string Class { get; set; }
        public string Detachment { get; set; }
        public string Family { get; set; }
        public string Image { get; set; }
    }
}
